load("@roo_testing//roo_testing/emulation:arduino.bzl", "roo_arduino_example")

roo_arduino_example(
    name = "loglevel",
    sketch = "loglevel.ino",
    visibility = ["//visibility:public"],
    deps = ["//:roo_logging"],
)
