load("@roo_testing//roo_testing/emulation:arduino.bzl", "roo_arduino_example")

roo_arduino_example(
    name = "logging_custom_objects",
    sketch = "logging_custom_objects.ino",
    visibility = ["//visibility:public"],
    deps = ["//:roo_logging"],
)
