load("@roo_testing//roo_testing/emulation:arduino.bzl", "roo_arduino_example")

roo_arduino_example(
    name = "debug_mode",
    sketch = "debug_mode.ino",
    visibility = ["//visibility:public"],
    deps = ["//:roo_logging"],
)
