load("@roo_testing//roo_testing/emulation:arduino.bzl", "roo_arduino_example")

roo_arduino_example(
    name = "per_module",
    sketch = "per_module.ino",
    visibility = ["//visibility:public"],
    deps = ["//:roo_logging"],
)
