load("@roo_testing//roo_testing/emulation:arduino.bzl", "roo_arduino_example")

roo_arduino_example(
    name = "custom_failure_function",
    sketch = "custom_failure_function.ino",
    visibility = ["//visibility:public"],
    deps = ["//:roo_logging"],
)
